language: python
python:
  - "3.6"  
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python tests/APIServiceTest.py
  - python tests/ImageDownoloadRequestTest.py
  - python tests/ImageRequestsTest.py